stp={"sd": "sekolah dasar", "smp" : "sekolah menengah pertama", "sma" : "sekolah menengah atas","paud": "pendidikan anak usia dini",
"ipa":"ilmu pengetahuan alam","spk":"sistem pendukung keputusan","atk":"alat tulis kantor","bifas":"bidang fasilitas dan aset",
"uad":"universitas ahmad dahlan","mk":"mata kuliah","ro":"reserve osmosis","ood":"object oriented design","bhs":"bahasa","web":"website",
"tik":"teknologi informasi dan komunikasi","html":"hypertext markup language","jst":"jaringan syaraf tiruan","mtk":"matematika",
"cbr":"case based reasoning","pd":"pada","cv":"commanditaire vennootschap","yk":"yogyakarta","tcp":"transmission control protocol",
"ip":"internet protocol","ids":"intrusion detection system","dgn":"dengan","degn":"dengan","komdat":"komunikasi data",
"jarkom":"jaringan komputer","sms":"short message service","j2me":"java 2 micro edition","m-sev":"mtronik indosat",
"bpn":"badan pertanahan nasional","kab.":"kabupaten","sk":"studi kasus","ahp":"analytic hierarchy process","gap":"group algoritma programming",
"api":"aplication programming interface","it":"islam terpadu","e-government":"electonic government","adm":"architecture development method",
"soa":"service oriented architecture","diy":"daerah istimewa yogyakarta","pt":"perseroan terbatas","fti":"fakultas teknologi industri",
"rs":"rumah sakit","pku":"pusat kesehatan umum","pp":"pimpinan pusat","ti":"teknologi informasi","crm":"customer relationship management",
"disperindagkop":"dinas perindustrian perdagangan koperasi","ukm":"usaha kecil dan menengah",
"dishubkominfo":"dinas perhubungan komunikasi dan informasi","php":"hypertext prepocessor","e-commerce":"electronic commerce",
"fb":"facebook","sig":"sistem informasi geografis","1":"satu","2":"dua","3":"tiga","4":"empat","5":"lima","6":"enam","7":"tujuh","8":"delapan",
"9":"sembilan","10":"sepuluh","11":"sebelas","12":"dua belas","13":"tiga belas","14":"empat belas","15":"lima belas","sk":"studi kasus",
"si":"sistem informasi","m-government":"mobile government","kpa":"komisi perlindungan anak","rc4":"rivest code 4","fps":"frame per second",
"seo":"search engine optimization","bar":"behaviorally anchored rating scales","lbs":"location based service","ikm":"industri kecil menengah",
"smk":"sekolah menengah kejuruan","mts":"madrasah tsanawiyah","isp":"internet service provider","saw":"simple additive weighting",
"prodi":"program studi","gmap":"google map","sim":"sistem informasi management","ahc":"agglomerative hierarchical clustering",
"itil":"information technology infrastructure library","cbc":"chiper block chaining","e-learning":"electonic learning",
"e-readiness":"electronic readiness","hiv":"human immunodeficiency virus","aids":"acquired immuno deficiency syndrome",
"risc":"reduced instruction set computers","tea":"tiny encryption algoritm","3d":"tiga dimensi","akap":"antar kota antar provinsi",
"dslr":"digital single lens reflex","wap":"wireless application protocol","mtsn":"madrasah tsanawiyah negeri","kkn":"kuliah kerja nyata",
"pcc":"per connection classifier","kopma":"koperasi mahasiswa","btm":"baitut tamwil muhammadiyah","scm":"supply chain management",
"aes":"advanced encrption standard","cbs":"chiper block substitusi","m-edukasi":"mobile edukasi","gps":"global positioning system",
"vpn":"virtual private metwork","fp-growth":"frequent pattern growth","yk":"yogyakarta","e-menu":"electronic menu","lan":"local area network",
"atm":"anjungan tunai mandiri","e-library":"electronic library","rfid":"radio frequency identification","k3":"kesehatan dan keselamatan kerja",
"2d":"dua dimensi","3d":"tiga dimensi","ssh":"secure shell","knn":"k-nearest neighbor","e-kos":"electronic kost","e-masjid":"electronic masjid",
"qr code":"quick response code","e-voting":"electronic voting","eoq":"economic order quantity","iris":"integrated reporting is simple",
"mvc":"model view controller","e-marketplace":"electronic marketplace","e-supply":"electronic supply","e-toke":"electronic toke",
"qos":"quality of service","e-office":"electronic office","glcm":"geray level co-occurence matrix","ux":"user experience","ui":"user interface",
"l2tp":"layer dua tunneling protocol","e-collection":"electronic collection","bms":"broadcast management system","hmvc":"hierarki model view controller",
"ac2dm":"android cloud to device messaging","gcm":"google cloud messaging","csi":"customer satisfaction index","pos":"point of sale",
"snn":"shared nearest neighbor","regex":"reguler expression","opengl":"open graphics library","mtb":"myres bridgstype indicator",
"foldarm":"fast online dynamic assosiation rule mining","togaf":"the open group architecture framework","anfis":"adaptive neuro fuzzy inference",
"wep":"wired equivalent privacy","wpa":"wifi protected access","sql":"structured query language","iso":"internasional organization for standardization",
"ucd":"user centered design","tam":"technology acceptance model","cdc":"central of disease control","rest":"representation state transfer",
"s.a":"service automation","qos":"quality of service","cbq":"class babsed queue","tbf":"token bucket filter","htb":"hierarchi token bucket",
"e-book":"buku elektonik","wammi":"website analysis measuremment inventory","tdd":"test driven development","som":"self organizing map",
"cart":"classification and regression tree","ucp":"use case point","tf":"term frequency","idf":"inverse document frequency","css":"cross site scripting",
"vsm":"vector space model","tcsd":"task centered design","mtma":"man in the middle attack","rsa":"rivest shamir adieman",
"idfif":"integrated digital forensics investigation","v2":"versi dua", "manajement":"management"}